export default function HowItWorks() {
    const steps = [
        { title: "User Onboarding", desc: "Register and verify KYC (PAN, GST, IEC, etc.)" },
        { title: "Trade Creation", desc: "List products and negotiate contracts auto-generated by the system." },
        { title: "Document Automation", desc: "Invoice, Packing List, Shipping Bill, etc. are auto-filled." },
        { title: "Compliance Check", desc: "Real-time integration with DGFT and Customs for rule checks." },
        { title: "Secure Payments", desc: "Bank-based escrow system with milestone releases." },
        { title: "Logistics Tracking", desc: "AI-route selection and GPS-enabled shipment tracking." },
        { title: "Insurance & Loans", desc: "Integrated shipment insurance and pre-approved trade loans." }
    ];

    return (
        <div className="container section">
            <h1 className="section-title">How Manthan Works</h1>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(600px, 1fr))', gap: '2rem' }}>
                {steps.map((step, index) => (
                    <div key={index} className="card" style={{ display: 'flex', alignItems: 'flex-start' }}>
                        <div style={{
                            backgroundColor: 'var(--primary-red)',
                            color: 'white',
                            width: '40px',
                            height: '40px',
                            borderRadius: '50%',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            fontWeight: 'bold',
                            marginRight: '1.5rem',
                            flexShrink: 0
                        }}>
                            {index + 1}
                        </div>
                        <div>
                            <h3 style={{ marginBottom: '0.5rem' }}>{step.title}</h3>
                            <p>{step.desc}</p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
